# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-octicons

# Global
source: ./
destination: ./_site
safe: false
include: 
  [
  ".htaccess"
  ]
exclude: 
  [
  vendor
  Gemfile,
  Gemfile.lock
  ]
keep_files: [".git", ".svn"]
timezone: Asia/Shanghai
#encoding: ENCODING

# Compile
future: true
lsi: false
limit_posts: 0
#incremental: BOOL
profile: false
permalink: /:year/:month/:day/:title/
paginate: 1
paginate_path: "page/:num"

# Service
port: 4002
host: 127.0.0.1
baseurl: "/jekyll-csdn"
detach: false
#url: http://localhost:4001

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Collections
collections:
  spare_collection:
    output: true
    permalink: /sparecollection/:path/
