# Gems
gems:
  - jekyll-admin
  - jekyll-archives
  - jekyll-assets
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-sitemap

# Global
source: ./
destination: ./docs
safe: false
include: 
  [
  ".htaccess"
  ]
exclude: 
  [
  vendor,
  Gemfile,
  Gemfile.lock,
  README.md,
  LICENSE
  ]
keep_files: [".git", ".svn"]
timezone: Asia/Shanghai
#encoding: ENCODING

# Compile
future: true
lsi: false
limit_posts: 0
#incremental: BOOL
profile: false
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"

# Service
port: 4002
host: 127.0.0.1
baseurl: "/jekyll-theme-csdn"
repository: "moyummy/jekyll-theme-csdn"
detach: false
#url: http://localhost:4001

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Collections
collections:
  spare_collection:
    output: true
    permalink: /sparecollection/:path/

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layouts:
    year: archives
    month: archives
    tag: archives
    category: archives
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'
